version: 2
jobs:
  release:
    steps:
      - run: npm run semantic-release
workflows:
  version: 2
  build_and_deploy:
    docker:
      - image: circleci/node:12.6
    jobs:
      - checkout
      - release
