version: 2
jobs:
  release/release:
    docker:
      - image: circleci/node:12.6
    steps:
      - checkout
      - run:
          command: npm i && npm run semantic-release
workflows:
  Release Workflow:
    jobs:
      - release/release
  version: 2
