version: 2
jobs:
  release/release:
    docker:
      - image: circleci/node:12.6
    steps:
      # moves source code to working directory
      - checkout
      - run:
          name: 'Install dependencies'
          command: npm i
      - run:
          name: 'Setup github credentials'
          command: |
            echo 'export GH_TOKEN="FOO"' >> $BASH_ENV
workflows:
  Release Workflow:
    jobs:
      - release/release
  version: 2
